export enum ErrorCategories {
  ACCOUNT_ACCESS = 'account-access',
  ACCOUNT_SETTINGS = 'account-settings',
  CREATE_DOCUMENT_ACCESS_REQUEST = 'create-document-access-request',
  DOCUMENT_DOWNLOAD = 'document-download',
  DRAFT_DELETE = 'draft-delete',
  DRAFT_LOAD = 'draft-load',
  ENTITY_BASIC = 'entity-basic',
  FEE_INFO = 'fee-info',
  HISTORY_REGISTRATIONS = 'history-registrations',
  HISTORY_SEARCHES = 'history-searches',
  REGISTRATION_CREATE = 'registration-create',
  REGISTRATION_DELETE = 'registration-delete',
  REGISTRATION_LOAD = 'registration-load',
  REGISTRATION_SAVE = 'registration-save',
  REPORT_GENERATION = 'report-generation',
  SEARCH = 'search',
  SEARCH_COMPLETE = 'seach-complete',
  SEARCH_UPDATE = 'search-update',
  LTSA_REQUEST = 'ltsa-request'
}
