export enum SearchTypes {
  AIRCRAFT = 'AIRCRAFT_DOT',
  BUSINESS_DEBTOR = 'BUSINESS_DEBTOR',
  INDIVIDCUAL_DEBTOR = 'INDIVIDUAL_DEBTOR',
  MHR_NUMBER = 'MHR_NUMBER',
  REGISTRATION_NUMBER = 'REGISTRATION_NUMBER',
  SERIAL_NUMBER = 'SERIAL_NUMBER'
}
