export enum LocationChangeTypes {
  TRANSPORT_PERMIT = 'TRANSPORT_PERMIT',
  TRANSPORT_PERMIT_SAME_PARK = 'TRANSPORT_PERMIT_SAME_PARK',
  TRANSPORT_PERMIT_CANCEL = 'TRANSPORT_PERMIT_CANCEL',
  REGISTERED_LOCATION = 'REGISTERED_LOCATION'
}
