export enum UnitNoteDocTypes {

  NOTICE_OF_CAUTION = 'CAU',
  CONTINUED_NOTE_OF_CAUTION = 'CAUC',
  EXTENSION_TO_NOTICE_OF_CAUTION = 'CAUE',
  NOTE_CANCELLATION = 'NCAN',
  CONFIDENTIAL_NOTE = 'NCON',
  PUBLIC_NOTE = 'NPUB',
  RESTRAINING_ORDER = 'REST',
  NOTICE_OF_TAX_SALE = 'TAXN',
  DECAL_REPLACEMENT = 'REG_102',
  NON_RESIDENTIAL_EXEMPTION = 'EXNR',
  RESIDENTIAL_EXEMPTION_ORDER = 'EXRS'
}

export enum UnitNoteStatusTypes {
  ACTIVE,
  CANCELLED,
  EXPIRED
}
