codecov:
  require_ci_to_pass: true
  branch: development
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: 75%
        flags:
          - pprapi
          - mhrapi
      ui:
        target: 50%
        flags:
          - pprui

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  pprapi:
    paths:
      - ppr-api/src/ppr-api
    carryforward: true
  pprui:
    paths:
      - ppr-ui/src
    carryforward: true
  mhrapi:
    paths:
      - mhr-api/src/mhr-api
    carryforward: true
