import { APIRegistrationTypes } from '@/enums'

export const SecuredPartyRestrictedList = [
  APIRegistrationTypes.LIEN_UNPAID_WAGES,
  APIRegistrationTypes.PROCEEDS_CRIME_NOTICE,
  APIRegistrationTypes.HERITAGE_CONSERVATION_NOTICE,
  APIRegistrationTypes.INSURANCE_PREMIUM_TAX,
  APIRegistrationTypes.PETROLEUM_NATURAL_GAS_TAX,
  APIRegistrationTypes.FOREST,
  APIRegistrationTypes.LOGGING_TAX,
  APIRegistrationTypes.CARBON_TAX,
  APIRegistrationTypes.PROVINCIAL_SALES_TAX,
  APIRegistrationTypes.RURAL_PROPERTY_TAX,
  APIRegistrationTypes.INCOME_TAX,
  APIRegistrationTypes.MOTOR_FUEL_TAX,
  APIRegistrationTypes.EXCISE_TAX,
  APIRegistrationTypes.MAINTENANCE_LIEN,
  APIRegistrationTypes.MANUFACTURED_HOME_NOTICE,
  APIRegistrationTypes.OTHER,
  APIRegistrationTypes.MINERAL_LAND_TAX,
  APIRegistrationTypes.PROPERTY_TRANSFER_TAX,
  APIRegistrationTypes.SCHOOL_ACT,
  APIRegistrationTypes.MISC_MINERAL_RESOURCE,
  APIRegistrationTypes.CROWN_MINING_TAX,
  APIRegistrationTypes.CROWN_CORP_CAPITAL_TAX,
  APIRegistrationTypes.CROWN_CONSUMPTION_TRANSITION_TAX,
  APIRegistrationTypes.CROWN_HOTEL_ROOM_TAX,
  APIRegistrationTypes.CROWN_SOCIAL_SERVICE_TAX,
  APIRegistrationTypes.TRANSITION_TAX_LIEN,
  APIRegistrationTypes.TOBACCO_TAX,
  APIRegistrationTypes.SPECULATION_VACANCY_TAX
]
