export { default as HomeCertification } from './HomeCertification.vue'
export { default as HomeSections } from './HomeSections.vue'
export { default as AddEditHomeSections } from './AddEditHomeSections.vue'
export { default as ManufacturerMakeModel } from './ManufacturerMakeModel.vue'
export { default as OtherInformation } from './OtherInformation.vue'
