export enum ReviewRegTypes {
    DECAL_REPLACE = 'DECAL_REPLACE',
    EXEMPTION_NON_RES = 'EXEMPTION_NON_RES',
    EXEMPTION_RES = 'EXEMPTION_RES',
    MHREG = 'MHREG',
    MHREG_CONVERSION = 'MHREG_CONVERSION',
    PERMIT = 'PERMIT',
    PERMIT_EXTENSION = 'PERMIT_EXTENSION',
    REG_STAFF_ADMIN = 'REG_STAFF_ADMIN',
    TRAND = 'TRAND',
    TRANS = 'TRANS',
    TRANS_AFFIDAVIT = 'TRANS_AFFIDAVIT',
    TRANS_ADMIN = 'TRANS_ADMIN',
    TRANS_WILL = 'TRANS_WILL',
    AMENDMENT = 'AMENDMENT'
}

export enum ReviewStatusTypes {
    PAY_PENDING = 'PAY_PENDING',
    PAY_CANCELLED = 'PAY_CANCELLED',
    NEW = 'NEW',
    IN_REVIEW = 'IN_REVIEW',
    ON_HOLD = 'ON_HOLD',
    APPROVED = 'APPROVED',
    DECLINED = 'DECLINED',
}
