export * from './discharge'
export * from './exemption'
export * from './renew'
export * from './newMhrRegistration'
export * from './newRegistration'
export * from './amendment'
export * from './mhrSearch'
export * from './userAccess'
export { default as MhrInformation } from './mhrInformation/MhrInformation.vue'
export { default as MhrUnitNote } from './mhrInformation/MhrUnitNote.vue'
export { default as MhrHistory } from './mhrInformation/MhrHistory.vue'
export { default as MhrTransportPermit } from './mhrInformation/MhrTransportPermit.vue'
export { default as Dashboard } from './Dashboard.vue'
export { default as Search } from './Search.vue'
