"""0002_party_code_account

Revision ID: 5c1f6bb801a8
Revises: ce62234b2378
Create Date: 2025-06-26 15:30:14.845271

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c1f6bb801a8'
down_revision = 'ce62234b2378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('client_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_codes_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('client_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_codes_account_id'))
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
