# Schema detail doc
# https://docs.python.org/3/library/logging.config.html#dictionary-schema-details
version: 1
disable_existing_loggers: True

formatters:
  mainFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(filename)s:%(lineno)d'
    datefmt: '%Y-%m-%d %H:%M:%S'
  appFormatter:
    format: '{"timestamp": "%(asctime)s", "severity": "%(levelname)s", "message": "%(message)s", "logger": "%(name)s", "file": "%(filename)s:%(lineno)d"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  main:
    class: logging.StreamHandler
    level: WARNING
    formatter: mainFormatter
    stream: ext://sys.stdout
  app:
    class: logging.StreamHandler
    level: INFO
    formatter: appFormatter
    stream: ext://sys.stdout

loggers:
  doc_api:
    level: WARNING
    handlers: [main]
    propagate: no
  werkzeug:
    level: WARNING
    handlers: [main]
    propagate: no
  appLogger:
    level: INFO
    handlers: [app]
    propagate: no

root:
  level: INFO
  handlers: []