import { FeeSummaryDefaults } from '@/composables/fees/enums'
import { UnitNoteDocTypes, UnitNoteStatusTypes } from '@/enums'
import { PartyIF } from '@/interfaces'

export interface UnitNoteIF {
  documentType: UnitNoteDocTypes
  documentId: string
  documentRegistrationNumber?: string
  documentDescription?: string
  createDateTime?: string
  effectiveDateTime?: string
  expiryDateTime?: string
  remarks?: string
  additionalRemarks?: string
  givingNoticeParty?: PartyIF
  hasNoPersonGivingNotice?: boolean // local property not sent to API
  status?: UnitNoteStatusTypes
  destroyed?: boolean
  nonResidentialReason?: string
  cancelledDocumentType?: string
  cancelledDocumentDescription?: string
  cancelledDocumentRegistrationNumber?: string
}

export interface CancelUnitNoteIF extends UnitNoteIF {
  cancelledDocumentDescription: string,
  cancelledDocumentRegistrationNumber: string
  cancelledDocumentType: string
}

// Adds UI specific properties to the UnitNoteIF interface for rendering panels
export interface UnitNotePanelIF extends UnitNoteIF {
  cancelledDateTime?: string
  additionalUnitNotes?: Array<UnitNotePanelIF>
}

export interface UnitNoteInfoIF {
  header: string
  dropdownText: string
  dropdownIcon?: string
  fee: FeeSummaryDefaults
  panelHeader?: string
  generatedRemarks?: string // remarks generated by the api to be added to remarks on the panel
}
