import { FeeSummaryDefaults } from '@/composables/fees/enums'
import { UnitNoteDocTypes, UnitNoteStatusTypes } from '@/enums'
import { PartyIF } from '@/interfaces'

export interface UnitNoteIF {
  documentType: UnitNoteDocTypes
  documentId?: string
  documentRegistrationNumber?: string
  documentDescription?: string
  createDateTime?: string
  effectiveDateTime?: string
  expiryDateTime?: string
  remarks?: string
  additionalRemarks?: string
  givingNoticeParty?: PartyIF
  status?: UnitNoteStatusTypes
  destroyed?: boolean
}

export interface UnitNoteInfoIF {
  header: string,
  dropdownText: string,
  dropdownIcon?: string,
  fee: FeeSummaryDefaults,
  panelHeader?: string,
  generatedRemarks?: string // remarks generated by the api to be added to remarks on the panel
}
