"""0008_ppr_reg_num_s

Revision ID: 333dd24963c0
Revises: 639ae66d100b
Create Date: 2026-05-19 10:49:45.182625

"""
from alembic import op
from alembic_utils.pg_function import PGFunction
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.

# revision identifiers, used by Alembic.
revision = '333dd24963c0'
down_revision = '4ee06cbac24b'  #'639ae66d100b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('registration_num_s_seq', start=100000, increment=1)))


    # Manually added replace current definition. ###
    public_get_registration_num_last = PGFunction(
        schema="public",
        signature="get_registration_num()",
        definition="RETURNS VARCHAR\n    LANGUAGE plpgsql\n    AS\n    $$\n    BEGIN\n        RETURN trim(to_char(nextval('registration_num_r_seq'), '000000')) || 'R';\n    END\n    ; \n    $$"
    )

    public_get_registration_num = PGFunction(
        schema="public",
        signature="get_registration_num()",
        definition="RETURNS VARCHAR\n    LANGUAGE plpgsql\n    AS\n    $$\n    BEGIN\n        RETURN trim(to_char(nextval('registration_num_s_seq'), '000000')) || 'S';\n    END\n    ; \n    $$"
    )
    # Manually added drop current definition. ###
    op.drop_entity(public_get_registration_num_last)
    op.create_entity(public_get_registration_num)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Manually added revert to previous definition. ###
    public_get_registration_num_last = PGFunction(
        schema="public",
        signature="get_registration_num()",
        definition="RETURNS VARCHAR\n    LANGUAGE plpgsql\n    AS\n    $$\n    BEGIN\n        RETURN trim(to_char(nextval('registration_num_r_seq'), '000000')) || 'R';\n    END\n    ; \n    $$"
    )

    public_get_registration_num = PGFunction(
        schema="public",
        signature="get_registration_num()",
        definition="RETURNS VARCHAR\n    LANGUAGE plpgsql\n    AS\n    $$\n    BEGIN\n        RETURN trim(to_char(nextval('registration_num_s_seq'), '000000')) || 'S';\n    END\n    ; \n    $$"
    )
    op.drop_entity(public_get_registration_num)
    # Manually added create previous definition. ###
    op.create_entity(public_get_registration_num_last)

    # Manually added drop sequence commands ###
    op.execute(DropSequence(Sequence('registration_num_s_seq')))

    # ### end Alembic commands ###
