"""Test Update.

Revision ID: 0bef490ea1d0
Revises: 701902c9ea3e
Create Date: 2022-01-22 11:34:19.797040

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bef490ea1d0'
down_revision = '701902c9ea3e'
branch_labels = None
depends_on = None

# Removed match_individual_name, searchkey_business_name updates from the script: run manually.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('last_name_split1', sa.String(length=50), nullable=True))
    op.add_column('parties', sa.Column('last_name_split2', sa.String(length=50), nullable=True))
    op.add_column('parties', sa.Column('last_name_split3', sa.String(length=50), nullable=True))
    op.add_column('parties', sa.Column('first_name_split1', sa.String(length=50), nullable=True))
    op.add_column('parties', sa.Column('first_name_split2', sa.String(length=50), nullable=True))
    op.add_column('parties', sa.Column('first_name_char1', sa.String(length=1), nullable=True))
    op.add_column('parties', sa.Column('first_name_char2', sa.String(length=1), nullable=True))
    op.add_column('parties', sa.Column('first_name_key_char1', sa.String(length=1), nullable=True))
    op.add_column('parties', sa.Column('bus_name_base', sa.String(length=150), nullable=True))
    op.add_column('parties', sa.Column('bus_name_key_char1', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_parties_first_name_split1'), 'parties', ['first_name_split1'], unique=False)
    op.create_index(op.f('ix_parties_first_name_split2'), 'parties', ['first_name_split2'], unique=False)
    op.create_index(op.f('ix_parties_last_name_split1'), 'parties', ['last_name_split1'], unique=False)
    op.create_index(op.f('ix_parties_last_name_split2'), 'parties', ['last_name_split2'], unique=False)
    op.create_index(op.f('ix_parties_last_name_split3'), 'parties', ['last_name_split3'], unique=False)

 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parties_last_name_split3'), table_name='parties')
    op.drop_index(op.f('ix_parties_last_name_split2'), table_name='parties')
    op.drop_index(op.f('ix_parties_last_name_split1'), table_name='parties')
    op.drop_index(op.f('ix_parties_first_name_split2'), table_name='parties')
    op.drop_index(op.f('ix_parties_first_name_split1'), table_name='parties')

    # Manually added
  
    op.drop_column('parties', 'first_name_split2')
    op.drop_column('parties', 'first_name_split1')
    op.drop_column('parties', 'last_name_split3')
    op.drop_column('parties', 'last_name_split2')
    op.drop_column('parties', 'last_name_split1')

    op.drop_column('parties', 'first_name_char1')
    op.drop_column('parties', 'first_name_char2')
    op.drop_column('parties', 'first_name_key_char1')
    op.drop_column('parties', 'bus_name_base')
    op.drop_column('parties', 'bus_name_key_char1')

    # ### end Alembic commands ###
