"""add_login_source_to_users

Revision ID: 1ef89b6dbbcd
Revises: ee0598ac597e
Create Date: 2022-11-24 11:07:29.994136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef89b6dbbcd'
down_revision = 'ee0598ac597e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_source', sa.String(length=200)))


def downgrade():
    op.drop_column('users', 'login_source')
