"""gc description alter to text

Revision ID: 1fa4df7e1c7a
Revises: 2f237ad5effe
Create Date: 2021-11-29 16:26:34.567816

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '1fa4df7e1c7a'
down_revision = '2f237ad5effe'
branch_labels = None
depends_on = None

# Change general_collateral.description column data type to text.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('general_collateral', 'description',
               existing_type=sa.VARCHAR(length=4000),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('general_collateral', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4000),
               existing_nullable=False)
    # ### end Alembic commands ###
