"""empty message

Revision ID: 233a32fc2c67
Revises: 1fa4df7e1c7a
Create Date: 2021-12-06 16:49:36.378020

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '233a32fc2c67'
down_revision = '1fa4df7e1c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_search_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=2), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('sim_val_business', sa.Float(), nullable=True),
    sa.Column('sim_val_first_name', sa.Float(), nullable=True),
    sa.Column('sim_val_last_name', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['search_type'], ['search_types.search_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_criteria', sa.JSON(), nullable=False),
    sa.Column('run_time', sa.Numeric(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['test_search_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_searches_batch_id'), 'test_searches', ['batch_id'], unique=False)
    op.create_table('test_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'SIMILAR', name='matchtype'), nullable=False),
    sa.Column('source', sa.Enum('API', 'LEGACY', name='source'), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['test_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_search_results_search_id'), table_name='test_search_results')
    op.drop_table('test_search_results')
    op.drop_index(op.f('ix_test_searches_batch_id'), table_name='test_searches')
    op.drop_table('test_searches')
    op.drop_table('test_search_batches')
    # ### end Alembic commands ###
