"""add user extra registrations table

Revision ID: 2b13f89aa1b3
Revises: fc0ad427d293
Create Date: 2021-09-22 15:16:14.337246

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.

# revision identifiers, used by Alembic.
revision = '2b13f89aa1b3'
down_revision = 'fc0ad427d293'
branch_labels = None
depends_on = None

# Increase clientReferenceId length from 20 to 50.
# Create user_extra_registrations table to manage user added financing statements.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('user_extra_registration_seq', start=1, increment=1)))
    op.create_table('user_extra_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_extra_registrations_account_id'), 'user_extra_registrations', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_extra_registrations_registration_number'), 'user_extra_registrations', ['registration_number'], unique=False)
    op.alter_column('registrations', 'client_reference_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('search_requests', 'client_reference_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_requests', 'client_reference_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('registrations', 'client_reference_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_extra_registrations_registration_number'), table_name='user_extra_registrations')
    op.drop_index(op.f('ix_user_extra_registrations_account_id'), table_name='user_extra_registrations')
    op.drop_table('user_extra_registrations')
    op.execute(DropSequence(Sequence('user_extra_registration_seq')))
    # ### end Alembic commands ###
