"""update previous_financing_statements

Revision ID: 5d5f7c7753f1
Revises: d2614cc8fde9
Create Date: 2021-08-16 13:36:13.483006

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d5f7c7753f1'
down_revision = 'd2614cc8fde9'
branch_labels = None
depends_on = None

# Change requested by Bob: alter date data types from timestamp to varchar(7).
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previous_financing_statements', 'cb_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('previous_financing_statements', 'cr_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('previous_financing_statements', 'mhr_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previous_financing_statements', 'mhr_date',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('previous_financing_statements', 'cr_date',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('previous_financing_statements', 'cb_date',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
