"""add account bcol id mapping table

Revision ID: 8fb9d269a9d4
Revises: d3f96fb8b8e5
Create Date: 2021-10-21 14:14:09.695266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.

# revision identifiers, used by Alembic.
revision = '8fb9d269a9d4'
down_revision = 'd3f96fb8b8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Added manually
    op.execute(CreateSequence(Sequence('account_bcol_id_seq', start=1, increment=1)))

    op.create_table('account_bcol_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('bconline_account', sa.Integer(), nullable=False),
    sa.Column('crown_charge_ind', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_bcol_ids_account_id'), 'account_bcol_ids', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_bcol_ids_account_id'), table_name='account_bcol_ids')
    op.drop_table('account_bcol_ids')

    # Added manually
    op.execute(DropSequence(Sequence('account_bcol_id_seq')))

    # ### end Alembic commands ###
