"""empty message

Revision ID: c868a87ae202
Revises: 9fefc7beceec
Create Date: 2021-12-09 12:19:26.050711

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c868a87ae202'
down_revision = '9fefc7beceec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_search_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=2), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('sim_val_business', sa.Float(), nullable=True),
    sa.Column('sim_val_first_name', sa.Float(), nullable=True),
    sa.Column('sim_val_last_name', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['search_type'], ['search_types.search_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_criteria', sa.Text(), nullable=False),
    sa.Column('run_time', sa.Float(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['test_search_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_searches_batch_id'), 'test_searches', ['batch_id'], unique=False)
    op.create_table('test_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=1), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['test_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_search_results_search_id'), 'test_search_results', ['search_id'], unique=False)

    # this was never added to a previous migration and is needed when setting up db for first time
    # op.add_column('user_extra_registrations', sa.Column('removed_ind', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_search_results_search_id'), table_name='test_search_results')
    op.drop_table('test_search_results')
    op.drop_index(op.f('ix_test_searches_batch_id'), table_name='test_searches')
    op.drop_table('test_searches')
    op.drop_table('test_search_batches')
    # ### end Alembic commands ###
