"""correct parties.party_type length

Revision ID: d2614cc8fde9
Revises: df84f254282d
Create Date: 2021-07-30 10:52:38.292229

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'd2614cc8fde9'
down_revision = 'df84f254282d'
branch_labels = None
depends_on = None

# Correct parties.party_type length: alter from 30 to 2.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties', 'party_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parties', 'party_type',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
