"""update user profile definition

Revision ID: d3f96fb8b8e5
Revises: 2b13f89aa1b3
Create Date: 2021-10-18 15:45:33.906745

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = 'd3f96fb8b8e5'
down_revision = '2b13f89aa1b3'
branch_labels = None
depends_on = None

# Update user profile to add registrations table and miscellaneous (future) preferences.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('registrations_table', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('misc_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'misc_preferences')
    op.drop_column('user_profiles', 'registrations_table')

    # ### end Alembic commands ###
