"""Add verification report

Revision ID: f27b7c10458f
Revises: 0bef490ea1d0
Create Date: 2022-02-17 16:32:22.217827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text as sql_text
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.

# revision identifiers, used by Alembic.
revision = 'f27b7c10458f'
down_revision = '0bef490ea1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_ts', sa.DateTime(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('doc_storage_url', sa.String(length=1000), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reports_create_ts'), 'verification_reports', ['create_ts'], unique=False)
    op.create_index(op.f('ix_verification_reports_registration_id'), 'verification_reports', ['registration_id'], unique=False)
    # Added manually
    op.execute(CreateSequence(Sequence('verification_report_id_seq', start=1, increment=1)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reports_registration_id'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_reports_create_ts'), table_name='verification_reports')
    op.drop_table('verification_reports')
    # Added manually
    op.execute(DropSequence(Sequence('verification_report_id_seq')))
    # ### end Alembic commands ###
