export { default as Parties } from './Parties.vue'
export { default as EditDebtor } from './EditDebtor.vue'
export { default as Debtors } from './Debtors.vue'
export { default as EditParty } from './EditParty.vue'
export { default as PartySearch } from './PartySearch.vue'
export { default as SecuredParties } from './SecuredParties.vue'
