export * from './auth'
export * from './discharge'
export * from './renew'
export * from './newRegistration'
export * from './amendment'
export { default as Dashboard } from './Dashboard.vue'
export { default as Search } from './Search.vue'
