export { default as TransferDetails } from './TransferDetails.vue'
export { default as TransferDetailsReview } from './TransferDetailsReview.vue'
export { default as ConfirmCompletion } from './ConfirmCompletion.vue'
export { default as TransferType } from './TransferType.vue'
export { default as DeathCertificate } from './DeathCertificate.vue'
export { default as SupportingDocuments } from './SupportingDocuments.vue'
export { default as HomeOwnersGroupError } from './HomeOwnersGroupError.vue'
