-- Script to create PPR type objects.

CREATE OR REPLACE TYPE SEARCH_RESULT_OBJ is object 
 (MATCH CHAR(1 BYTE),
  DOCUMENT_NUMBER VARCHAR2(8 BYTE),
  BLOCK_NUMBER NUMBER,
  RESULT VARCHAR2(150 BYTE),
  JARO NUMBER);

CREATE TYPE SEARCH_RESULT_TAB is table of SEARCH_RESULT_OBJ;
