-- Script to create PPR PL/SQL packages.

-- search_key_pkg begin
CREATE OR REPLACE PACKAGE SEARCH_KEY_PKG AS
/******************************************************************************

   NAME:       PPR_KEY

   PURPOSE: CREATE SEARCH KEY

 

   REVISIONS:

   Ver        Date        Author           Description

   ---------  ----------  ---------------  ------------------------------------

   1.0        2021-02-03      BBOWLES       1. Created this package.

******************************************************************************/

FUNCTION BUSNAMEKEY(BUSINESSNAME IN VARCHAR2) RETURN VARCHAR2;
FUNCTION LASTFIRST (LASTNAME IN VARCHAR2) RETURN VARCHAR2;
FUNCTION LASTSECOND(LASTNAME IN VARCHAR2) RETURN VARCHAR2;
FUNCTION FIRSTNAME(FIRSTNAME IN VARCHAR2) RETURN VARCHAR2;
FUNCTION VEHICLE(SERIALNUMBER IN VARCHAR2) RETURN NUMBER;
FUNCTION MHR(MHRNUMBER IN VARCHAR2) RETURN VARCHAR2;
FUNCTION AIRCRAFT(AIRCRAFTNUMBER IN VARCHAR2) RETURN VARCHAR2;

END SEARCH_KEY_PKG;
/

CREATE OR REPLACE PACKAGE BODY SEARCH_KEY_PKG AS

 
FUNCTION BUSNAMEKEY(BUSINESSNAME IN VARCHAR2) RETURN VARCHAR2

IS

 V_BUS_SRCH_KEY VARCHAR2(150);


 BEGIN

       V_BUS_SRCH_KEY :=

       REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE

      (REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE

      (REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE

      (REGEXP_REPLACE

      (BUSINESSNAME,'^0000|^000|^00|^0|^THE | THE |\([^()]*\)','')

       ,'CORPORATION|CORP|COMPANY|CO\.|LTD|INCORPORATED|INC$|INC.|INCORPOREE|LIMITED|LIMITEE|LTEE|LTD|ASSOCIATION$|ASSOC$|ASSN$|NON PERSONAL LIABILITY$|UNLIMITED LIABILITY COMPANY|N P L$|NPL$|PARTNERSHIP|SOCIETY$|SOC$','')

       ,'BRITISH COLUMBIA|BRITISHCOLUMBIA','BC')

      ,'&','AND')

      ,'#','NUMBER')

      ,'1','ONE'),'2','TWO'),'3','THREE'),'4','FOUR'),'5','FIVE'),'6','SIX'),'7','SEVEN'),'8','EIGHT'),'9','NINE'),'0','ZERO')

      ,'TEN','ONEZERO'),'TWENTY','TWOZERO'),'THIRTY','THREEERO'),'FOURTY','FOURZERO'),'FOURTY','FOURZERO'),'FIFTY','FIVEZERO'),'SIXTY','SIXERO'),'SEVENTY','SEVENZERO'),'EIGHTY','EIGHTZERO'),'NINETY','NINEZERO')

      ,'[^0-9A-Za-z]'

      ,'',1,0,'i');

  RETURN V_BUS_SRCH_KEY;

END;


 FUNCTION LASTFIRST(LASTNAME IN VARCHAR2) RETURN VARCHAR2

IS

 V_LASTFIRST VARCHAR2(30);

BEGIN

  V_LASTFIRST := REGEXP_SUBSTR(LASTNAME, '[^- ]+');

  RETURN V_LASTFIRST;

END;


 FUNCTION LASTSECOND(LASTNAME IN VARCHAR2) RETURN VARCHAR2

IS

 V_LASTSECOND VARCHAR2(30);

BEGIN

  V_LASTSECOND := REGEXP_REPLACE(REGEXP_REPLACE(LASTNAME,'[^-]*-'),'[^ ]* ');

  RETURN V_LASTSECOND;

END;


 FUNCTION FIRSTNAME(FIRSTNAME IN VARCHAR2) RETURN VARCHAR2

IS

 V_FIRST_NAME VARCHAR2(92);

V_FIRST_1 VARCHAR2(30);

V_FIRST_2 VARCHAR2(30);

V_FIRST_3 VARCHAR2(30);

BEGIN

  V_FIRST_1 := REGEXP_SUBSTR(FIRSTNAME, '[^- ]+');

  V_FIRST_2 := REGEXP_SUBSTR(FIRSTNAME,'[^-|^ ]+',1,2);

  V_FIRST_3 := REGEXP_SUBSTR(FIRSTNAME,'[^-|^ ]+',1,3);

  V_FIRST_NAME := V_FIRST_1||' '||V_FIRST_2||' '||V_FIRST_3;

  RETURN V_FIRST_NAME;

END;


 FUNCTION VEHICLE(SERIALNUMBER IN VARCHAR2) RETURN NUMBER

IS

 V_SRCHVIN NUMBER;

BEGIN

  V_SRCHVIN :=

              LPAD(SUBSTR(REGEXP_REPLACE(REGEXP_REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE

             (SERIALNUMBER,'I',1),'L',1),'Z',2),'H',4),'Y',4),'C',6),'G',6),'B',8),'[AD-FJ-X]',0),'[^0-9]',''),-LEAST(LENGTH(SERIALNUMBER), 6)),6,'0');

  RETURN V_SRCHVIN;

END;


 FUNCTION MHR(MHRNUMBER IN VARCHAR2) RETURN VARCHAR2

IS

 V_SRCHVIN VARCHAR2(7);

BEGIN

  V_SRCHVIN := REGEXP_REPLACE(MHRNUMBER,'^0000|^000|^00|^0|\s','');

END;


 FUNCTION AIRCRAFT(AIRCRAFTNUMBER IN VARCHAR2) RETURN VARCHAR2

IS

 V_SRCHVIN VARCHAR2(7);

BEGIN

  V_SRCHVIN := REGEXP_REPLACE(AIRCRAFTNUMBER,'\s|-','');

END;

 

END SEARCH_KEY_PKG;
INSERT INTO draft(draft_id, document_number, account_id, create_ts, registration_type_cl, registration_type_cd,
                  registration_number, update_ts, draft, registration_id)
  VALUES(300000000, 'D-T-0001', 'PS12345', sysdate, 'PPSALIEN', 'SA', 'TEST0001', null, '{}', 300000000);
INSERT INTO financing_statement(financing_id, state_type_cd, expire_date, life, discharged, renewed, registration_number)
  VALUES(300000000, 'ACT', sysdate + 730, 2, null , null, 'TEST0001')
;
INSERT INTO registration(registration_id, financing_id, registration_number, base_reg_number, registration_type_cd,
                         registration_type_cl, registration_ts, document_number, life, lien_value,
                         surrender_date, account_id, client_reference_id, pay_invoice_id, pay_path)
    VALUES(300000000, 300000000, 'TEST0001', null, 'SA', 'PPSALIEN', sysdate, 'D-T-0001', 2,
           null, null, 'PS12345', 'TEST-SA-0001', null, null)
;
-- search_key_pkg end

