declare
   c int;
begin
       select count(*) into c from user_procedures where object_type = 'FUNCTION' and object_name = 'GET_DRAFT_DOCUMENT_NUMBER';
       if c = 1 then
          execute immediate 'DROP FUNCTION get_draft_document_number';
       end if;
end;
/
CREATE FUNCTION get_draft_document_number
  RETURN VARCHAR2
  IS
  BEGIN
    RETURN 'D'||to_char(DOCUMENT_NUMBER_SEQ.nextval);
  END; 
/

declare
   d int;
begin
       select count(*) into d from user_procedures where object_type = 'FUNCTION' and object_name = 'GET_REGISTRATION_NUM';
       if d = 1 then
          execute immediate 'DROP FUNCTION get_registration_num';
       end if;
end;
/
CREATE FUNCTION get_registration_num
  RETURN VARCHAR2
  IS
  BEGIN
    RETURN to_char(registration_num_seq.nextval) || 'B';
  END;
/

declare
   e int;
begin
       select count(*) into e from user_procedures where object_type = 'FUNCTION' and object_name = 'MATCH_INDIVIDUAL_NAME';
       if e = 1 then
          execute immediate 'DROP FUNCTION match_individual_name';
       end if;
end;
/
CREATE FUNCTION match_individual_name(lastname IN VARCHAR2, firstname IN VARCHAR2)
  RETURN SYS.ODCINUMBERLIST
  IS
    V_LAST_NAME   VARCHAR2(50);
    V_LAST_1      VARCHAR2(50);
    V_LAST_2      VARCHAR2(50);
    V_FIRST_NAME  VARCHAR2(50);
    V_FIRST_1     VARCHAR2(50);
    V_FIRST_2     VARCHAR2(50);
    V_FIRST_3     VARCHAR2(50);
    V_IDS         SYS.ODCINUMBERLIST;
  BEGIN
    V_LAST_NAME := SEARCH_KEY_pkg.LASTNAME(LASTNAME);
    V_LAST_1 := REGEXP_SUBSTR(V_LAST_NAME, '[^ ]+');
    V_LAST_2 := REGEXP_SUBSTR(V_LAST_NAME, '[^ ]+',1,2);   
    V_FIRST_NAME := SEARCH_KEY_pkg.FIRSTNAME(FIRSTNAME);
    V_FIRST_1 := REGEXP_SUBSTR(V_FIRST_NAME, '[^ ]+');
    V_FIRST_2 := REGEXP_SUBSTR(V_FIRST_NAME, '[^ ]+',1,2);
    V_FIRST_3 := REGEXP_SUBSTR(V_FIRST_NAME, '[^ ]+',1,2);

    SELECT party_id
      BULK COLLECT INTO V_IDS
      FROM party
  WHERE REGISTRATION_ID_END IS NULL
  AND UTL_MATCH.JARO_WINKLER_SIMILARITY(UPPER(LAST_NAME_KEY),UPPER(V_LAST_NAME)) >= 79
  AND (UTL_MATCH.JARO_WINKLER_SIMILARITY(UPPER(FIRST_NAME_KEY),UPPER(V_FIRST_NAME)) >= 85
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR FIRST_NAME_KEY IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_NAME) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  )
  OR
  REGISTRATION_ID_END IS NULL
  AND V_LAST_1 = REGEXP_SUBSTR(LAST_NAME_KEY, '[^ ]+',1,2)
  AND (V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR FIRST_NAME_KEY IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_NAME) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  )
  OR
  REGISTRATION_ID_END IS NULL
  AND V_LAST_2 = REGEXP_SUBSTR(LAST_NAME_KEY, '[^ ]+')
  AND (V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR FIRST_NAME_KEY IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_NAME) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  )
  OR
  REGISTRATION_ID_END IS NULL
  AND V_LAST_2 = REGEXP_SUBSTR(LAST_NAME_KEY, '[^ ]+',1,2)
  AND (V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_1 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_2 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2)
  OR V_FIRST_3 = REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3)
  OR FIRST_NAME_KEY IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_NAME) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_1) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_2) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+')      IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,2) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  OR REGEXP_SUBSTR(FIRST_NAME_KEY, '[^ ]+',1,3) IN(SELECT NAME FROM NICKNAME_PPR WHERE NAME_ID IN (SELECT NAME_ID FROM NICKNAME_PPR WHERE(V_FIRST_3) = NAME))
  );
  
    RETURN V_IDS;
  END;
/