-- country type codes
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TM', 'TURKMENISTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TC', 'TURKS AND CAICOS ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TV', 'TUVALU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('UG', 'UGANDA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('UA', 'UKRAINE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AE', 'UNITED ARAB EMIRATES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GB', 'UNITED KINGDOM');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('US', 'UNITED STATES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('UY', 'URUGUAY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ME', 'MONTENEGRO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('RS', 'SERBIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IM', 'ISLE OF MAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GG', 'GUERNSEY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('JE', 'JERSEY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BQ', 'BONAIRE, ST EUSTATIUS AND SABA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CW', 'CURACAO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SX', 'SINT MAARTEN(DUTCH PART)');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SS', 'SOUTH SUDAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MF', 'SAINT MARTIN(FRENCH PART)');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AX', 'ALAND ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BL', 'SAINT BARTHELEMY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FX', 'FRANCE, METROPOLITAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TA', 'TRISTAN DA CUNHA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('XZ', 'KOSOVO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('UZ', 'UZBEKISTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VU', 'VANUATU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VE', 'VENEZUELA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VN', 'VIET NAM');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VG', 'VIRGIN ISLANDS, BRITISH');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VI', 'VIRGIN ISLANDS, U.S.');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('WF', 'WALLIS AND FUTUNA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('EH', 'WESTERN SAHARA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('YE', 'YEMEN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('YU', 'YUGOSLAVIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ZM', 'ZAMBIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ZW', 'ZIMBABWE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AF', 'AFGHANISTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AL', 'ALBANIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DZ', 'ALGERIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AS', 'AMERICAN SAMOA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AD', 'ANDORRA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AO', 'ANGOLA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AI', 'ANGUILLA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AQ', 'ANTARCTICA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AG', 'ANTIGUA AND BARBUDA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AR', 'ARGENTINA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AM', 'ARMENIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AW', 'ARUBA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AU', 'AUSTRALIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AT', 'AUSTRIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AZ', 'AZERBAIJAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BS', 'BAHAMAS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BH', 'BAHRAIN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BD', 'BANGLADESH');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BB', 'BARBADOS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BY', 'BELARUS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BE', 'BELGIUM');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BZ', 'BELIZE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BJ', 'BENIN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BM', 'BERMUDA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BT', 'BHUTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BO', 'BOLIVIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BA', 'BOSNIA AND HERZEGOVINA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BW', 'BOTSWANA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BV', 'BOUVET ISLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BR', 'BRAZIL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IO', 'BRITISH INDIAN OCEAN TERRITORY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BN', 'BRUNEI DARUSSALAM');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BG', 'BULGARIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BF', 'BURKINA FASO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('BI', 'BURUNDI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KH', 'CAMBODIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CM', 'CAMEROON');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CA', 'CANADA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CV', 'CAPE VERDE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KY', 'CAYMAN ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CF', 'CENTRAL AFRICAN REPUBLIC');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TD', 'CHAD');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CL', 'CHILE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CN', 'CHINA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CX', 'CHRISTMAS ISLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CC', 'COCOS (KEELING) ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CO', 'COLOMBIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KM', 'COMOROS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CG', 'CONGO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CK', 'COOK ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CR', 'COSTA RICA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CI', 'COTE D''''IVOIRE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HR', 'CROATIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CU', 'CUBA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CY', 'CYPRUS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CZ', 'CZECH REPUBLIC');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DK', 'DENMARK');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DJ', 'DJIBOUTI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DM', 'DOMINICA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DO', 'DOMINICAN REPUBLIC');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('EC', 'ECUADOR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('EG', 'EGYPT');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SV', 'EL SALVADOR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GQ', 'EQUATORIAL GUINEA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ER', 'ERITREA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('EE', 'ESTONIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ET', 'ETHIOPIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FK', 'FALKLAND ISLANDS (MALVINAS)');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FO', 'FAROE ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FJ', 'FIJI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FI', 'FINLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FR', 'FRANCE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GF', 'FRENCH GUIANA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PF', 'FRENCH POLYNESIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TF', 'FRENCH SOUTHERN TERRITORIES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GA', 'GABON');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GM', 'GAMBIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GE', 'GEORGIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('DE', 'GERMANY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GH', 'GHANA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GI', 'GIBRALTAR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GR', 'GREECE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GL', 'GREENLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GD', 'GRENADA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GP', 'GUADELOUPE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GU', 'GUAM');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GT', 'GUATEMALA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GN', 'GUINEA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GW', 'GUINEA-BISSAU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GY', 'GUYANA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HT', 'HAITI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VA', 'HOLY SEE (VATICAN CITY STATE)');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HN', 'HONDURAS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HK', 'HONG KONG');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('HU', 'HUNGARY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IS', 'ICELAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IN', 'INDIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ID', 'INDONESIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IR', 'IRAN, ISLAMIC REPUBLIC OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IQ', 'IRAQ');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IE', 'IRELAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IL', 'ISRAEL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('IT', 'ITALY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('JM', 'JAMAICA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('JP', 'JAPAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('JO', 'JORDAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KZ', 'KAZAKHSTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KE', 'KENYA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KI', 'KIRIBATI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KP', 'KOREA, DEMOCRATIC PEOPLE''''S REPUBLIC OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KR', 'KOREA, REPUBLIC OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KW', 'KUWAIT');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KG', 'KYRGYZSTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LA', 'LAO PEOPLE''''S DEMOCRATIC REPUBLIC');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LV', 'LATVIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LB', 'LEBANON');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LS', 'LESOTHO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LR', 'LIBERIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LY', 'LIBYA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LI', 'LIECHTENSTEIN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LT', 'LITHUANIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LU', 'LUXEMBOURG');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MO', 'MACAO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC ');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MG', 'MADAGASCAR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MW', 'MALAWI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MY', 'MALAYSIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MV', 'MALDIVES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ML', 'MALI');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MT', 'MALTA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MH', 'MARSHALL ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MQ', 'MARTINIQUE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MR', 'MAURITANIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MU', 'MAURITIUS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('YT', 'MAYOTTE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MX', 'MEXICO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('FM', 'MICRONESIA, FEDERATED STATES OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MD', 'MOLDOVA, REPUBLIC OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MC', 'MONACO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MN', 'MONGOLIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MS', 'MONTSERRAT');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MA', 'MOROCCO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MZ', 'MOZAMBIQUE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MM', 'MYANMAR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NA', 'NAMIBIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NR', 'NAURU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NP', 'NEPAL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('AN', 'NETHERLANDS ANTILLES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NL', 'NETHERLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NC', 'NEW CALEDONIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NZ', 'NEW ZEALAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NI', 'NICARAGUA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NE', 'NIGER');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NG', 'NIGERIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NU', 'NIUE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NF', 'NORFOLK ISLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('MP', 'NORTHERN MARIANA ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('NO', 'NORWAY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('OM', 'OMAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PK', 'PAKISTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PW', 'PALAU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PS', 'PALESTINIAN TERRITORY, OCCUPIED');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PA', 'PANAMA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PG', 'PAPUA NEW GUINEA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PY', 'PARAGUAY');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PE', 'PERU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PH', 'PHILIPPINES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PN', 'PITCAIRN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PL', 'POLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PT', 'PORTUGAL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PR', 'PUERTO RICO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('QA', 'QATAR');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('RE', 'REUNION');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('RO', 'ROMANIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('RU', 'RUSSIAN FEDERATION');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('RW', 'RWANDA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SH', 'SAINT HELENA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('KN', 'SAINT KITTS AND NEVIS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LC', 'SAINT LUCIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('PM', 'SAINT PIERRE AND MIQUELON');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('VC', 'SAINT VINCENT AND THE GRENADINES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('WS', 'SAMOA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SM', 'SAN MARINO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ST', 'SAO TOME AND PRINCIPE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SA', 'SAUDI ARABIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SN', 'SENEGAL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SC', 'SEYCHELLES');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SL', 'SIERRA LEONE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SG', 'SINGAPORE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SK', 'SLOVAKIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SI', 'SLOVENIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SB', 'SOLOMON ISLANDS');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SO', 'SOMALIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ZA', 'SOUTH AFRICA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('ES', 'SPAIN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('LK', 'SRI LANKA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SD', 'SUDAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SR', 'SURINAME');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SJ', 'SVALBARD AND JAN MAYEN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SZ', 'SWAZILAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SE', 'SWEDEN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('CH', 'SWITZERLAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('SY', 'SYRIAN ARAB REPUBLIC');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TW', 'TAIWAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TJ', 'TAJIKISTAN');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TZ', 'TANZANIA, UNITED REPUBLIC OF');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TH', 'THAILAND');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TL', 'TIMOR-LESTE');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TG', 'TOGO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TK', 'TOKELAU');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TO', 'TONGA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TT', 'TRINIDAD AND TOBAGO');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TN', 'TUNISIA');
Insert into COUNTRY_TYPES
   (COUNTRY_TYPE_CD, COUNTRY_DESC)
 Values
   ('TR', 'TURKEY');
