-- province types
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AA', 'US', 'ARMED FORCES - AMERICAS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AE', 'US', 'ARMED FORCES - OTHER');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AP', 'US', 'ARMED FORCES - PACIFIC');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('BC', 'CA', 'BRITISH COLUMBIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AB', 'CA', 'ALBERTA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('ON', 'CA', 'ONTARIO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NB', 'CA', 'NEW BRUNSWICK');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('QC', 'CA', 'QUEBEC');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('YT', 'CA', 'YUKON TERRITORIES');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('PE', 'CA', 'PRINCE EDWARD ISLAND');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MB', 'CA', 'MANITOBA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NL', 'CA', 'NEWFOUNDLAND AND LABRADOR');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NT', 'CA', 'NORTHWEST TERRITORIES');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NS', 'CA', 'NOVA SCOTIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('SK', 'CA', 'SASKATCHEWAN');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NU', 'CA', 'NUNAVUT');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AK', 'US', 'ALASKA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AL', 'US', 'ALABAMA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AR', 'US', 'ARKANSAS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AS', 'US', 'AMERICAN SAMOA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('AZ', 'US', 'ARIZONA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('CA', 'US', 'CALIFORNIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('CO', 'US', 'COLORADO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('CT', 'US', 'CONNECTICUT');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('DC', 'US', 'DISTRICT OF COLUMBIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('DE', 'US', 'DELAWARE');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('FL', 'US', 'FLORIDA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('FM', 'US', 'FED. STATES');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('GA', 'US', 'GEORGIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('GU', 'US', 'GUAM');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('HI', 'US', 'HAWAII');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('IA', 'US', 'IOWA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('ID', 'US', 'IDAHO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('IL', 'US', 'ILLINOIS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('IN', 'US', 'INDIANA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('KS', 'US', 'KANSAS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('KY', 'US', 'KENTUCKY');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('LA', 'US', 'LOUISIANA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MA', 'US', 'MASSACHUSETTS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MD', 'US', 'MARYLAND');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('ME', 'US', 'MAINE');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MH', 'US', 'MARSHALL ISLANDS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MI', 'US', 'MICHIGAN');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MN', 'US', 'MINNESOTA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MO', 'US', 'MISSOURI');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MP', 'US', 'N. MARIANA ISLANDS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MS', 'US', 'MISSISSIPPI');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('MT', 'US', 'MONTANA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NC', 'US', 'NORTH CAROLINA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('ND', 'US', 'NORTH DAKOTA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NE', 'US', 'NEBRASKA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NH', 'US', 'NEW HAMPSHIRE');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NJ', 'US', 'NEW JERSEY');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NM', 'US', 'NEW MEXICO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NV', 'US', 'NEVADA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('NY', 'US', 'NEW YORK');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('OH', 'US', 'OHIO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('OK', 'US', 'OKLAHOMA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('OR', 'US', 'OREGON');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('PA', 'US', 'PENNSYLVANIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('PR', 'US', 'PUERTO RICO');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('PW', 'US', 'PALAU');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('RI', 'US', 'RHODE ISLAND');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('SC', 'US', 'SOUTH CAROLINA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('SD', 'US', 'SOUTH DAKOTA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('TN', 'US', 'TENNESSEE');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('TX', 'US', 'TEXAS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('UM', 'US', 'U.S. MINOR ISLANDS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('UT', 'US', 'UTAH');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('VA', 'US', 'VIRGINIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('VI', 'US', 'VIRGIN ISLANDS');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('VT', 'US', 'VERMONT');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('WA', 'US', 'WASHINGTON');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('WI', 'US', 'WISCONSIN');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('WV', 'US', 'WEST VIRGINIA');
Insert into PROVINCE_TYPES
   (PROVINCE_TYPE_CD, COUNTRY_TYPE_CD, PROVINCE_DESC)
 Values
   ('WY', 'US', 'WYOMING');
