export { default as ButtonFooter } from './ButtonFooter.vue'
export { default as ErrorContact } from './ErrorContact.vue'
export { default as RegistrationFee } from './RegistrationFee.vue'
export { default as FolioNumber } from './FolioNumber.vue'
export { default as Stepper } from './Stepper.vue'
export { default as Tombstone } from './Tombstone.vue'
