export enum FeeCodes {
  AMENDMENT = 'FSCHG',
  CHANGE = 'FSCHG',
  DISCHARGE = 'FSDIS',
  FINANCING_NO_CHARGE = 'NCREG',
  FINANCING_LIFE_YEAR = 'FSREG',
  FINANCING_INFINITE = 'INFRG',
  RENEWAL_LIFE_YEAR = 'FSREN',
  RENEWAL_INFINITE = 'INFRN',
  SEARCH = 'SERCH'
}
