export enum LocationChangeTypes {
  TRANSPORT_PERMIT = 'TRANSPORT_PERMIT',
  TRANSPORT_PERMIT_SAME_PARK = 'TRANSPORT_PERMIT_SAME_PARK',
  TRANSPORT_PERMIT_CANCEL = 'CANCEL_PERMIT',
  REGISTERED_LOCATION = 'REGISTERED_LOCATION',
  EXTEND_PERMIT = 'EXTEND_PERMIT',
  PERMIT_EXTEND_API = 'PERMIT_EXTEND',
  CREATE_NEW_PERMIT = 'CREATE_NEW_PERMIT'
}
