export enum FeeSummaryTypes {
  AMEND = 'amend',
  DISCHARGE = 'discharge',
  NEW = 'new',
  RENEW = 'renew',
  MHSEARCH = 'manufactured_home_search',
  MHR_COMBINED_SEARCH = 'combined_home_search',
  NEW_MHR = 'new_mhr',
  MHR_RE_REGISTRATION = 'mhr_re_registration',
  MHR_STAFF_CORRECTION = 'mhr_staff_correction',
  MHR_CLIENT_CORRECTION = 'mhr_client_correction',
  MHR_PUBLIC_AMENDMENT = 'mhr_public_amendment',
  MHR_TRANSFER = 'mhr_transfer',
  MHR_TRANSPORT_PERMIT = 'mhr_transport_permit',
  MHR_TRANSPORT_PERMIT_CANCEL = 'mhr_transport_permit_cancel',
  MHR_AMEND_TRANSPORT_PERMIT = 'mhr_amend_transport_permit',
  MHR_UNIT_NOTE = 'mhr_unit_note',
  RESIDENTIAL_EXEMPTION = 'residential_exemption',
  NON_RESIDENTIAL_EXEMPTION = 'non_residential_exemption',
  NO_FEE = 'no_fee',
}
