name: MHR API CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "mhr-api/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  mhr-api-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd.yaml@redeploy-cd-fix
    with:
      target: ${{ inputs.target }}
      app_name: "mhr-api"
      working_directory: "./mhr-api"
      cd_runner_version: "1.0.8"
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
