name: PPR API CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "ppr-api/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - uat
        - sandbox
        - prod

jobs:
  ppr-api-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "ppr-api"
      working_directory: "./ppr-api"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}