name: PPR API CI

on:
  pull_request:
    paths:
      - "ppr-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./ppr-api

jobs:
  ppr-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "ppr-api"
      working_directory: "./ppr-api"
      codecov_flag: "pprapi"
