name: ASSETS UI CD - GCP

on:
  push:
    branches:
      - main
    paths:
      - "ppr-ui/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod
      tagname:
        description: "Specify a previous version (git tag) to deploy"
        required: false
        default: ""

jobs:
  ppr-ui-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/ui-cd.yaml@main
    with:
      environment: ${{ inputs.environment }}
      tagname: ${{ inputs.tagname }}
      working_directory: "./ppr-ui"
    secrets:
      APP_NAME: "assets-ui"
      OP_CONNECT_URL: ${{ secrets.OP_CONNECT_URL }}
      OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
