name: "[TEST] pnpm v11 upgrade"

on:
  push:
    branches: ["test/pnpm-v11-upgrade"]
  workflow_dispatch:

jobs:
  test-pnpm-v11:
    uses: panish16/bcregistry-sre/.github/workflows/frontend-ci.yaml@feat/upgrade-pnpm-v11
    with:
      pnpm_version: 'latest-11'
      app_name: "ppr-ui"
      working_directory: "./ppr-ui"
      codecov_flag: "pprui"
      node_version: 24
